### PR TITLE
Proposal: Add section 'Installation from distro packages' to README.md

### PR DESCRIPTION
**Pull request by Firef0x**
Hello, @dohliam !

Appreciate your great job! :rose: I have submited this program in [Arch User Repository](https://aur.archlinux.org/packages/forvocl) so that `Arch Linux` users could install it easily with package manager. I think it's better to add section 'Installation from distro packages' to `README.md` to widely spread this news.

What's more, I decided to put section 'Installation from distro packages' prior to 'Usage' because I think user should read about how to install before how to use. :wink: 

Do you agree with me? Hope for your reply!

Yours sincerely! :bow:

### CODE REVIEW

**Comment by dohliam** [comment]
Great, thanks Firef0x! I'll merge this ASAP.

**Comment by dohliam** [comment]
Just noticed that the link to AUR [seems to be broken](https://aur.archlinux.org/packages/forvocl). Could you double check that it's the right link? Thanks!

**Comment by Firef0x** [comment]
Hello @dohliam ,

Well, I thought you probably would accept the merge, so I decided to wait until your merge so that I could get the latest git commit hash (i.e. [20150427.99b2c03](https://github.com/dohliam/forvocl/commit/99b2c03df2b136aecb5d6a875ddecb8451355c37))and update the install script accordingly.

I convince that the [link](https://aur.archlinux.org/packages/forvocl) works now.

Yours sincerely!

**Comment by dohliam** [comment]
Ah, that makes sense now! Thanks again :+1:

**Pull request merged**
